---
spring:
  datasource:
    url: jdbc:h2:mem
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: update
    show_sql: false
slack:
  nashorn:
    upload_token: A3ufMbZCPBvfUdXeAAmS
  webhook:
    url: https://hooks.slack.com/services/T0VD98HD0/Z0VQ29PQQ/aUZuWAk6jsSbuE35hwz9XcJf
  brew:
    brew_master_id: ASDF1234
    brew_master_username: frodo
  valid_command_tokens: asdf1234,qwert5678
