---
applications:
- name: coffee-bot-blue
  buildpack: java_buildpack
  path: build/libs/coffee-bot-${version}.jar
  env:
    app:
      version: ${version}
  memory: 1024M
  instances: 1
  services:
  - mysql
  no-route: true
